export function buildStylesheet(directed, weighted) {
  return [
    {
      selector: 'core',
      style: { 'background-opacity': 0 },
    },
    {
      selector: 'node',
      style: {
        'background-color': '#6d28d9',
        'background-fill': 'radial-gradient',
        'background-gradient-stop-colors': '#8b5cf6 #4c1d95',
        'background-gradient-stop-positions': '30% 100%',
        'border-color': '#5b21b6',
        'border-width': 2,
        'label': 'data(label)',
        'color': '#ffffff',
        'font-size': '14px',
        'font-weight': '600',
        'font-family': '"JetBrains Mono", "Fira Code", monospace',
        'text-valign': 'center',
        'text-halign': 'center',
        'width': 46,
        'height': 46,
        'overlay-padding': '6px',
        'shadow-blur': 12,
        'shadow-color': '#7c3aed',
        'shadow-opacity': 0.5,
        'shadow-offset-x': 0,
        'shadow-offset-y': 0,
      },
    },
    {
      selector: 'node.hovering',
      style: {
        'background-color': '#7c3aed',
        'background-fill': 'radial-gradient',
        'background-gradient-stop-colors': '#a78bfa #5b21b6',
        'background-gradient-stop-positions': '30% 100%',
        'border-color': '#7c3aed',
        'border-width': 3,
        'shadow-blur': 24,
        'shadow-opacity': 0.75,
      },
    },
    {
      selector: 'node.pending-source',
      style: {
        'background-color': '#dc2626',
        'background-fill': 'radial-gradient',
        'background-gradient-stop-colors': '#fca5a5 #b91c1c',
        'background-gradient-stop-positions': '25% 100%',
        'border-color': '#991b1b',
        'border-width': 3,
        'shadow-blur': 24,
        'shadow-color': '#ef4444',
        'shadow-opacity': 0.85,
        'shadow-offset-x': 0,
        'shadow-offset-y': 0,
      },
    },
    {
      selector: 'edge',
      style: {
        'width': 2,
        'line-color': '#64748b',
        'curve-style': 'bezier',
        'target-arrow-color': '#64748b',
        'target-arrow-shape': directed ? 'triangle' : 'none',
        'source-arrow-shape': 'none',
        'arrow-scale': 1.2,
        'label': weighted ? 'data(weight)' : '',
        'font-size': '12px',
        'font-family': '"JetBrains Mono", "Fira Code", monospace',
        'color': '#e2e8f0',
        'text-rotation': 'autorotate',
        'text-margin-y': -10,
        'text-background-color': '#1e1e2e',
        'text-background-opacity': weighted ? 1 : 0,
        'text-background-shape': 'roundrectangle',
        'text-background-padding': '3px',
      },
    },
    {
      selector: 'edge.hovering',
      style: {
        'line-color': '#93c5fd',
        'target-arrow-color': '#93c5fd',
        'width': 3,
      },
    },
    {
      selector: 'edge:selected',
      style: {
        'line-color': '#fbbf24',
        'target-arrow-color': '#fbbf24',
        'width': 3,
      },
    },
  ];
}
